version: 0.0
os: linux
files:
    - source: openspy-core
      destination: /var/openspy/
      mode: 777
hooks:
  BeforeInstall:
    - location: openspy-core/bootstrap.sh
      runas: root
  AfterInstall:
    - location: openspy-core/build.sh
      runas: root
  ApplicationStart:
    - location: openspy-core/boot.sh
      runas: root
